name 'clarifi_winsvc'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures clarifi_winsvc'
long_description 'Installs/Configures clarifi_winsvc'
version '0.1.0'
