name 'iis-website'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures iis-website'
long_description 'Installs/Configures iis-website'
version '0.1.0'
